### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by meishuu**
## Major version bumps
High chance of breakage:
- discord.js ^11.3.0 → [`d041cb2`](https://github.com/discordjs/discord.js/tree/d041cb2460a294b026e73750647647168ce7359a) (TODO: test this)
- babel ^6.26.0 → 7.0.0-beta.42
- babel-loader ^7.0.0 → 8.0.0-beta.2
- extract-text-webpack-plugin ^3.0.2 → 4.0.0-beta.0
- flow-bin ^0.63.1 → 0.68.0
- html-webpack-plugin ^2.28.0 → 3.0.7
- webpack ^3.10.0 → 4.1.1
- webpack-dev-middleware ^2.0.4 → 3.0.1
- webpack-manifest-plugin ^1.1.0 → 2.0.0-rc.2

Low chance of breakage:
- autoprefixer ^7.1.1 → 8.1.0
- eslint-loader ^1.7.1 → 2.0.0
- eslint-plugin-jsx-a11y ^5.1.1 → 6.0.3
- eslint-plugin-node ^5.2.1 → 6.0.1
- style-loader ^0.19.1 → 0.20.3
- url-loader ^0.6.2 → 1.0.1

## Other
- Removed `babel-preset-react-app` and `eslint-config-react-app`
- Now lint and prettify webpack config files
- Played with lint rules a little bit

### CODE REVIEW

**Comment by Uppun** [comment]
Oh is this just changes to update dependencies?

**Comment by meishuu** [comment]
@Uppun ye

the main ones are flow (no new errors 🙏) and discord.js (still need to test 🙅), the rest are just nice bonuses (and me getting to learn webpack 4 and nuking create-react-app leftovers *finally*)

**Comment by Uppun** [comment]
I'm actually not sure how to or what to review on this other than I guess see the changes and figure out what you did tbqh

**Comment by meishuu** [comment]
@Uppun this is mostly for your awareness although it does vaguely touch upon a couple parts of actual app code

if you *want*, you can check the changes to the babel and webpack and eslint configs but that's mostly a rabbit hole of research

merge is mostly just waiting on me actually testing this to make sure discord.js v12 doesn't break anything

**Pull request merged**
